### ISSUE TITLE
`fix_docs` does not work in the fastapi==0.136.1

### ISSUE THREAD

**Issue by dzhygun** [uriyyo/fastapi-filters#729]
After upgrade of fastapi, the `fix_docs` raises exception.

Fastapi versions:
 - fastapi==0.135.1
 + fastapi==0.136.1

Fastapi-filters version: 0.3.3

Exception:
```
  File "/home/dzhygun/dev/api/src/main.py", line 56, in <module>
    fix_docs(app)
    ~~~~~~~~^^^^^
  File "/home/dzhygun/dev/api/.venv/lib/python3.14/site-packages/fastapi_filters/docs.py", line 14, in fix_docs
    app.add_event_handler("startup", _fix_docs)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FastAPI' object has no attribute 'add_event_handler'. Did you mean: 'add_exception_handler'?
```

**Supposed:** Looks like Fastapi deprecated finally the app-lifecycle event hooks. They are now completely replaced with 
```
@asynccontextmanager
async def lifespan(app: FastAPI):
    ...
```

The fix must be simple: remove event handler from `fix_docs` and guide in docs to move `fix_docs` into the `lifespan`

**Comment by uriyyo** [comment]
@dzhygun Thanks, I will take a look 🙏

**Comment by uriyyo** [comment]
Hi @dzhygun,

This issue should be resolved in the new version `0.4.0`

**Comment by uriyyo** [comment]
Hi @dzhygun,

I'm closing this issue. Let me know if it's still not working for you
